recipe: default.v1

language: es

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  - name: DIETClassifier
    epochs: 200
    learning_rate: 0.002
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector

policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
    epochs: 150
    constrain_similarities: true
assistant_id: 20251008-191204-angry-cathode
